import { BulbOutlineIcon } from '@sanity/icons'
import { defineField, defineType } from 'sanity'

export const dailyPrompt = defineType({
  name: 'dailyPrompt',
  title: 'Daily Prompt',
  type: 'document',
  icon: BulbOutlineIcon,
  fields: [
    defineField({
      name: 'promptText',
      title: 'Prompt Text',
      type: 'text',
      description: 'The journaling prompt for the day',
      rows: 3,
      validation: (rule) => rule.required().min(10).max(300),
    }),
    defineField({
      name: 'date',
      title: 'Date',
      type: 'date',
      description: 'The date this prompt is assigned to',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'category' }],
      description: 'Optional category for organizing prompts',
    }),
    defineField({
      name: 'isActive',
      title: 'Is Active',
      type: 'boolean',
      description: 'Whether this prompt is currently active',
      initialValue: true,
    }),
    defineField({
      name: 'aiGenerated',
      title: 'AI Generated',
      type: 'boolean',
      description: 'Was this prompt generated by AI?',
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      prompt: 'promptText',
      date: 'date',
      aiGenerated: 'aiGenerated',
    },
    prepare({ prompt, date, aiGenerated }) {
      const formattedDate = date ? new Date(date).toLocaleDateString() : 'No date'
      const prefix = aiGenerated ? '🤖 ' : '✍️ '
      
      return {
        title: `${prefix}${prompt?.substring(0, 60)}${prompt?.length > 60 ? '...' : ''}`,
        subtitle: formattedDate,
      }
    },
  },
  orderings: [
    {
      title: 'Date, New to Old',
      name: 'dateDesc',
      by: [{ field: 'date', direction: 'desc' }],
    },
    {
      title: 'Date, Old to New',
      name: 'dateAsc',
      by: [{ field: 'date', direction: 'asc' }],
    },
  ],
})

