import { DocumentTextIcon } from '@sanity/icons'
import { defineArrayMember, defineField, defineType } from 'sanity'

export const journalEntry = defineType({
  name: 'journalEntry',
  title: 'Journal Entry',
  type: 'document',
  icon: DocumentTextIcon,
  fields: [
    defineField({
      name: 'title',
      title: 'Entry Title',
      type: 'string',
      description: 'A title for your journal entry',
      validation: (rule) => rule.required().max(100).warning('Keep titles concise for better readability'),
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'array',
      description: 'The main content of your journal entry',
      of: [
        defineArrayMember({
          type: 'block',
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'Heading 1', value: 'h1' },
            { title: 'Heading 2', value: 'h2' },
            { title: 'Heading 3', value: 'h3' },
            { title: 'Quote', value: 'blockquote' },
          ],
          lists: [
            { title: 'Bullet', value: 'bullet' },
            { title: 'Numbered', value: 'number' },
          ],
          marks: {
            decorators: [
              { title: 'Strong', value: 'strong' },
              { title: 'Emphasis', value: 'em' },
              { title: 'Underline', value: 'underline' },
            ],
          },
        }),
      ],
      validation: (rule) => rule.required().min(1).error('Journal entry content is required'),
    }),
    defineField({
      name: 'moodRating',
      title: 'Mood Rating',
      type: 'number',
      description: 'Rate your mood from 1 (very low) to 10 (very high)',
      validation: (rule) =>
        rule
          .required()
          .min(1)
          .max(10)
          .integer()
          .error('Mood rating must be a whole number between 1 and 10'),
      options: {
        list: [
          { title: '1 - Very Low', value: 1 },
          { title: '2 - Low', value: 2 },
          { title: '3 - Below Average', value: 3 },
          { title: '4 - Slightly Below Average', value: 4 },
          { title: '5 - Neutral', value: 5 },
          { title: '6 - Slightly Above Average', value: 6 },
          { title: '7 - Above Average', value: 7 },
          { title: '8 - Good', value: 8 },
          { title: '9 - Great', value: 9 },
          { title: '10 - Excellent', value: 10 },
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'aiCategories',
      title: 'AI Generated Categories',
      type: 'array',
      description: 'Categories automatically generated by AI based on entry content',
      of: [
        defineArrayMember({
          type: 'string',
        }),
      ],
      options: {
        layout: 'tags',
      },
      validation: (rule) => rule.unique().max(10).warning('Consider limiting to 10 categories for clarity'),
    }),
    defineField({
      name: 'userId',
      title: 'User ID',
      type: 'string',
      description: 'The ID of the user who created this entry',
      validation: (rule) => rule.required(),
      readOnly: true,
      hidden: false,
    }),
    defineField({
      name: 'createdAt',
      title: 'Created At',
      type: 'datetime',
      description: 'When this entry was created',
      initialValue: () => new Date().toISOString(),
      validation: (rule) => rule.required(),
      readOnly: true,
    }),
    defineField({
      name: 'updatedAt',
      title: 'Updated At',
      type: 'datetime',
      description: 'When this entry was last updated',
      readOnly: true,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      mood: 'moodRating',
      date: 'createdAt',
    },
    prepare({ title, mood, date }) {
      const formattedDate = date ? new Date(date).toLocaleDateString() : 'No date'
      const moodEmoji = mood >= 8 ? '😊' : mood >= 5 ? '😐' : '😔'
      
      return {
        title: title || 'Untitled Entry',
        subtitle: `${moodEmoji} Mood: ${mood}/10 • ${formattedDate}`,
      }
    },
  },
  orderings: [
    {
      title: 'Created Date, New',
      name: 'createdDateDesc',
      by: [{ field: 'createdAt', direction: 'desc' }],
    },
    {
      title: 'Created Date, Old',
      name: 'createdDateAsc',
      by: [{ field: 'createdAt', direction: 'asc' }],
    },
    {
      title: 'Mood Rating, High to Low',
      name: 'moodDesc',
      by: [{ field: 'moodRating', direction: 'desc' }],
    },
    {
      title: 'Mood Rating, Low to High',
      name: 'moodAsc',
      by: [{ field: 'moodRating', direction: 'asc' }],
    },
  ],
})

